// swift-tools-version: 5.10

import PackageDescription

let scrcpySources = [
    "app/src/adb/adb.c",
    "app/src/adb/adb_device.c",
    "app/src/adb/adb_parser.c",
    "app/src/adb/adb_tunnel.c",
    "app/src/audio_player.c",
    "app/src/audio_regulator.c",
    "app/src/clock.c",
    "app/src/compat.c",
    "app/src/control_msg.c",
    "app/src/controller.c",
    "app/src/decoder.c",
    "app/src/demuxer.c",
    "app/src/device_msg.c",
    "app/src/disconnect.c",
    "app/src/embedded.c",
    "app/src/events.c",
    "app/src/file_pusher.c",
    "app/src/fps_counter.c",
    "app/src/frame_buffer.c",
    "app/src/icon.c",
    "app/src/input_manager.c",
    "app/src/keyboard_sdk.c",
    "app/src/mouse_capture.c",
    "app/src/mouse_sdk.c",
    "app/src/opengl.c",
    "app/src/options.c",
    "app/src/packet_merger.c",
    "app/src/receiver.c",
    "app/src/recorder.c",
    "app/src/scrcpy.c",
    "app/src/screen.c",
    "app/src/sdl_hints.c",
    "app/src/server.c",
    "app/src/texture.c",
    "app/src/video_regulator.c",
    "app/src/hid/hid_gamepad.c",
    "app/src/hid/hid_keyboard.c",
    "app/src/hid/hid_mouse.c",
    "app/src/trait/frame_source.c",
    "app/src/trait/packet_source.c",
    "app/src/uhid/gamepad_uhid.c",
    "app/src/uhid/keyboard_uhid.c",
    "app/src/uhid/mouse_uhid.c",
    "app/src/uhid/uhid_output.c",
    "app/src/util/acksync.c",
    "app/src/util/audiobuf.c",
    "app/src/util/average.c",
    "app/src/util/env.c",
    "app/src/util/file.c",
    "app/src/util/intmap.c",
    "app/src/util/intr.c",
    "app/src/util/log.c",
    "app/src/util/memory.c",
    "app/src/util/net.c",
    "app/src/util/net_intr.c",
    "app/src/util/process.c",
    "app/src/util/process_intr.c",
    "app/src/util/rand.c",
    "app/src/util/sdl.c",
    "app/src/util/str.c",
    "app/src/util/strbuf.c",
    "app/src/util/term.c",
    "app/src/util/thread.c",
    "app/src/util/tick.c",
    "app/src/util/timeout.c",
    "app/src/sys/unix/file.c",
    "app/src/sys/unix/process.c",
]

let package = Package(
    name: "ScrcpyDesk",
    platforms: [.macOS(.v13)],
    products: [
        .executable(name: "ScrcpyDesk", targets: ["ScrcpyDesk"])
    ],
    targets: [
        .target(
            name: "CScrcpy",
            path: ".",
            sources: scrcpySources,
            publicHeadersPath: "desktop/macos/ScrcpyDesk/CScrcpy/include",
            cSettings: [
                .headerSearchPath("app/src"),
                .unsafeFlags([
                    "-std=c11",
                    "-D_DARWIN_C_SOURCE",
                    "-D_GNU_SOURCE",
                    "-D_POSIX_C_SOURCE=200809L",
                    "-D_XOPEN_SOURCE=700",
                    "-I/opt/homebrew/include",
                    "-I/usr/local/include",
                ]),
            ],
            linkerSettings: [
                .unsafeFlags(["-L/opt/homebrew/lib", "-L/usr/local/lib"]),
                .linkedLibrary("avformat"),
                .linkedLibrary("avcodec"),
                .linkedLibrary("avutil"),
                .linkedLibrary("swresample"),
                .linkedLibrary("SDL3"),
            ]
        ),
        .executableTarget(
            name: "ScrcpyDesk",
            dependencies: ["CScrcpy"],
            path: "desktop/macos/ScrcpyDesk/Sources/ScrcpyDesk"
        ),
    ],
    swiftLanguageVersions: [.v5]
)
