#ifndef SCRCPY_DESK_CONFIG_H
#define SCRCPY_DESK_CONFIG_H

#define HAVE_STRDUP 1
#define HAVE_ASPRINTF 1
#define HAVE_VASPRINTF 1
#define HAVE_NRAND48 1
#define HAVE_JRAND48 1
#define SCRCPY_VERSION "4.1"
#define PREFIX "/usr/local"
#define PORTABLE 1

#define DEFAULT_LOCAL_PORT_RANGE_FIRST 27183
#define DEFAULT_LOCAL_PORT_RANGE_LAST 27199

#endif
