#define SC_EVENT_NEW_FRAME                 SDL_USEREVENT
#define SC_EVENT_STREAM_STOPPED           (SDL_USEREVENT + 1)
#define SC_EVENT_SERVER_CONNECTION_FAILED (SDL_USEREVENT + 2)
#define SC_EVENT_SERVER_CONNECTED         (SDL_USEREVENT + 3)
#define SC_EVENT_USB_DEVICE_DISCONNECTED  (SDL_USEREVENT + 4)
