#define EVENT_NEW_FRAME                 SDL_USEREVENT
#define EVENT_STREAM_STOPPED           (SDL_USEREVENT + 1)
#define EVENT_SERVER_CONNECTION_FAILED (SDL_USEREVENT + 2)
#define EVENT_SERVER_CONNECTED         (SDL_USEREVENT + 3)
