#!/usr/bin/env bash
set -e
url="$1"
sum="$2"
dir="$3"
create_extract_dir="$4"

checksum() {
    local file="$1"
    local sum="$2"
    echo "$file: verifying checksum..."
    echo "$sum  $file" | sha256sum -c
}

get_file() {
    local url="$1"
    local file="$2"
    local sum="$3"
    if [[ -f "$file" ]]
    then
        echo "$file: found"
    else
        echo "$file: not found, downloading..."
        wget "$url" -O "$file"
    fi
    checksum "$file" "$sum"
}

extract() {
    local file="$1"
    local create_extract_dir="$2"
    echo "Extracting $file..."
    if [[ "$file" == *.zip ]]
    then
        if [[ -n "$create_extract_dir" ]]
        then
            unzip -q "$file" -d "$dir"
        else
            unzip -q "$file"
        fi
    elif [[ "$file" == *.tar.gz ]]
    then
        if [[ -n "$create_extract_dir" ]]
        then
            tar xf "$file" --one-top-level="$dir"
        else
            tar xf "$file"
        fi
    elif [[ "$file" == *.7z ]]
    then
        if [[ -n "$create_extract_dir" ]]
        then
            7z x "$file" -o"$dir"
        else
            7z x "$file"
        fi
    else
        echo "Unsupported file: $file"
        return 1
    fi
}

get_dep() {
    local url="$1"
    local sum="$2"
    local dir="$3"
    local create_extract_dir="$4"
    local file="${url##*/}"
    if [[ -d "$dir" ]]
    then
        echo "$dir: found"
    else
        echo "$dir: not found"
        get_file "$url" "$file" "$sum"
        extract "$file" "$create_extract_dir"
    fi
}

get_dep "$url" "$sum" "$dir" "$create_extract_dir"
