#!/usr/bin/env bash
set -e
url="$1"
sum="$2"
dir="$3"

checksum() {
    local file="$1"
    local sum="$2"
    echo "$file: verifying checksum..."
    echo "$sum  $file" | sha256sum -c
}

get_file() {
    local url="$1"
    local file="$2"
    local sum="$3"
    if [[ -f "$file" ]]
    then
        echo "$file: found"
    else
        echo "$file: not found, downloading..."
        wget "$url" -O "$file"
    fi
    checksum "$file" "$sum"
}

get_first_layer_dir_name() {
    local file="$1"

    if [[ "$file" == *.zip ]]
    then
        echo `unzip -Z -1 "$file" | head -n 1 | cut -d/ -f1`
    elif [[ "$file" == *.tar.gz ]]
    then
        echo `tar tf "$file" | head -n 1 | cut -d/ -f1`
    else
        echo "Unsupported file: $file"
        return 1
    fi
}

extract() {
    local file="$1"
    local dir="$2"

    mkdir -p "$dir"
    echo "Extracting $file..."
    if [[ "$file" == *.zip ]]
    then
        local folder_in_file=`get_first_layer_dir_name "$file"`

        ln -s . "$dir"/"$folder_in_file"
        unzip -q "$file" -d "$dir"
        rm "$dir"/"$folder_in_file"
    elif [[ "$file" == *.tar.gz ]]
    then
        tar xf "$file" --strip 1 -C "$dir"
    else
        echo "Unsupported file: $file"
        return 1
    fi
}

get_dep() {
    local url="$1"
    local sum="$2"
    local dir="$3"
    local file="${url##*/}"
    if [[ -d "$dir" ]]
    then
        echo "$dir: found"
    else
        echo "$dir: not found"
        get_file "$url" "$file" "$sum"
        extract "$file" "$dir"
    fi
}

get_dep "$url" "$sum" "$dir"
